export const deviceScriptData = [
  {
    last_name: 'Түмэнбаяр',
    first_name: 'Бямбасүрэн',
    birth_date: '2000-02-16',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-6500',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Очирбат',
    first_name: 'Энхболд',
    birth_date: '1982-10-26',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Seagate',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Очирбат',
    first_name: 'Тэмүүжин',
    birth_date: '1993-12-15',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Crucial',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Цогтбаатар',
    first_name: 'Цэрэндорж',
    birth_date: '2001-04-09',
    rank: 'Дэд ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Ганхуяг',
    first_name: 'Одгэрэл',
    birth_date: '1998-09-28',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-7500',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Мөнхбаяр',
    birth_date: '1989-08-19',
    rank: 'Хошууч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Crucial',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Ганхуяг',
    first_name: 'Бямбасүрэн',
    birth_date: '1989-09-10',
    rank: 'Хошууч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-7500',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Очирбат',
    first_name: 'Бямбасүрэн',
    birth_date: '1994-07-27',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Seagate',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Нямдорж',
    first_name: 'Тэмүүжин',
    birth_date: '1986-07-15',
    rank: 'Хошууч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Эрдэнэбилэг',
    first_name: 'Одгэрэл',
    birth_date: '1996-08-15',
    rank: 'Ахлах дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Энхтүвшин',
    birth_date: '1981-09-11',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Батбаатар',
    first_name: 'Бат-Эрдэнэ',
    birth_date: '1983-05-26',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Жаргалсайхан',
    first_name: 'Сүхбат',
    birth_date: '1982-03-17',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Төгөлдөр',
    birth_date: '1992-11-05',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Даваадорж',
    first_name: 'Билгүүн',
    birth_date: '1998-04-01',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Эрдэнэбилэг',
    first_name: 'Тэмүүжин',
    birth_date: '1985-09-16',
    rank: 'Хошууч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Төгөлдөр',
    birth_date: '1997-11-01',
    rank: 'Ахлах дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Жаргалсайхан',
    first_name: 'Ганбаяр',
    birth_date: '1990-04-09',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Түвшинбаяр',
    first_name: 'Даваасүрэн',
    birth_date: '2001-09-22',
    rank: 'Дэд ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Жаргалсайхан',
    first_name: 'Энхтүвшин',
    birth_date: '1990-01-26',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Жаргалсайхан',
    first_name: 'Хүрэлбаатар',
    birth_date: '2002-01-06',
    rank: 'Дэд ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Батбаатар',
    first_name: 'Ганбаяр',
    birth_date: '1981-10-02',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Чимэдцэрэн',
    first_name: 'Төгөлдөр',
    birth_date: '1998-01-09',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Төгөлдөр',
    birth_date: '1997-01-05',
    rank: 'Ахлах дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Нямдорж',
    first_name: 'Хүрэлбаатар',
    birth_date: '1993-04-21',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Баярсайхан',
    first_name: 'Бат-Эрдэнэ',
    birth_date: '1994-10-31',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Чимэдцэрэн',
    first_name: 'Жавхлан',
    birth_date: '1981-01-15',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Даваадорж',
    first_name: 'Сүхбат',
    birth_date: '1991-12-18',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-7500',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Чимэдцэрэн',
    first_name: 'Билгүүн',
    birth_date: '1982-05-28',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Түвшинбаяр',
    first_name: 'Энхболд',
    birth_date: '1996-07-27',
    rank: 'Ахлах дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-6500',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Очирбат',
    first_name: 'Цэрэндорж',
    birth_date: '1981-11-23',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i5-6500',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Нямдорж',
    first_name: 'Даваасүрэн',
    birth_date: '1982-10-01',
    rank: 'Дэд хурандаа',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-6500',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Crucial',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Kingston',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Жаргалсайхан',
    first_name: 'Цэрэндорж',
    birth_date: '1992-02-10',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-10400',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Цогтбаатар',
    first_name: 'Мөнхбаяр',
    birth_date: '1993-08-04',
    rank: 'Ахлах ахлагч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Samsung',
        keyboard: 'HP Classic',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR3',
        hdd_size: '256GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Dell KB216',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Чимэдцэрэн',
    first_name: 'Тэмүүжин',
    birth_date: '1997-04-14',
    rank: 'Ахлах дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo IdeaPad',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Logitech K120',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i7-9700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Даваадорж',
    first_name: 'Төгөлдөр',
    birth_date: '1998-09-02',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Crucial',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'PC',
      },
      {
        device_name: 'Lenovo ThinkCentre',
        cpu: 'Intel Core i5-10400',
        ram: '16GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'HP Classic',
        mouse: 'HP X1000',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Түмэнбаяр',
    first_name: 'Мөнхбаяр',
    birth_date: '1999-04-21',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR4',
        hdd_size: '1TB HDD',
        hdd_brand: 'Seagate',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i5-7500',
        ram: '8GB DDR3',
        hdd_size: '512GB SSD',
        hdd_brand: 'Samsung',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Ганхуяг',
    first_name: 'Тэмүүжин',
    birth_date: '1999-08-31',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell Latitude',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Logitech K120',
        mouse: 'HP X1000',
        type: 'PC',
      },
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i7-7700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Western Digital',
        keyboard: 'Dell KB216',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Сүхбат',
    first_name: 'Жавхлан',
    birth_date: '2000-12-13',
    rank: 'Дэслэгч',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'Dell OptiPlex',
        cpu: 'Intel Core i7-9700',
        ram: '16GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Kingston',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR4',
        hdd_size: '512GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'Нөүтбүүк',
      },
    ],
  },
  {
    last_name: 'Түмэнбаяр',
    first_name: 'Жавхлан',
    birth_date: '1995-07-22',
    rank: 'Ахмад',
    position: 'Сүлжээний инженер',
    devices: [
      {
        device_name: 'HP ProBook',
        cpu: 'Intel Core i5-10400',
        ram: '8GB DDR3',
        hdd_size: '1TB HDD',
        hdd_brand: 'Samsung',
        keyboard: 'Logitech K120',
        mouse: 'Logitech B100',
        type: 'PC',
      },
      {
        device_name: 'HP EliteDesk',
        cpu: 'Intel Core i7-7700',
        ram: '8GB DDR4',
        hdd_size: '256GB SSD',
        hdd_brand: 'Seagate',
        keyboard: 'Dell KB216',
        mouse: 'Dell MS116',
        type: 'Нөүтбүүк',
      },
    ],
  },
];
